version: "2"
services:
  base:
    image: node:10-alpine
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
  install:
    extends:
      service: base
    command: npm install
  build:
    extends:
      service: base
    command: npm run build
  tsc-watch:
    extends:
      service: base
    command: npm run tsc:watch